name: for_a_real_angel
description: For A Real Angel.

# MUDA TAMBÉM EM "values/internalVersion" <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
version: 0.5.2+13

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  soundpool: ^2.3.0
  #swipedetector: ^1.2.0
  url_launcher: ^6.1.5
  package_info_plus: ^1.4.3
  carousel_slider: ^4.1.1
  #audioplayers: ^1.0.1
  just_audio: ^0.9.28
  after_layout: ^1.2.0
  percent_indicator: ^4.2.2
  random_string: ^2.3.1

  # Firebase
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.2
  firebase_storage: ^10.3.4
  firebase_auth: ^3.6.1
  google_sign_in: ^5.4.0
  provider: ^6.0.3

  #intl_translation: ^0.17.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/
    - assets/files/
    - assets/files/n2/
    - assets/icons/
    - assets/music/
    - assets/sounds/
    - assets/chapters_json/
  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: fonts/Josefin_Sans/JosefinSans-Bold.ttf
          weight: 700

    - family: CourierPrime
      fonts:
        - asset: fonts/Courier_Prime/CourierPrime-Regular.ttf
        - asset: fonts/Courier_Prime/CourierPrime-Bold.ttf
          weight: 700

    - family: PTSerif
      fonts:
        - asset: fonts/PTSerif/PTSerif-Regular.ttf
        - asset: fonts/PTSerif/PTSerif-Italic.ttf
          style: italic
        - asset: fonts/PTSerif/PTSerif-Bold.ttf
          weight: 700
        - asset: fonts/PTSerif/PTSerif-BoldItalic.ttf
          style: italic
          weight: 700
